ALTER TABLE `char`
MODIFY COLUMN `pow`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `luk`,
MODIFY COLUMN `sta`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `pow`,
MODIFY COLUMN `wis`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `sta`,
MODIFY COLUMN `spl`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `wis`,
MODIFY COLUMN `con`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `spl`,
MODIFY COLUMN `crt`  int(11) UNSIGNED NOT NULL DEFAULT 0 AFTER `con`;
